# Generated by Django 4.0.3 on 2022-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesses',
            name='correct_word',
            field=models.CharField(default='false', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guesses',
            name='guesses',
            field=models.CharField(default='false', max_length=30),
            preserve_default=False,
        ),
    ]
