# Generated by Django 4.0.3 on 2022-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_guesses_correct_word_guesses_guesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesses', models.CharField(max_length=30)),
                ('correct_word', models.CharField(max_length=5)),
            ],
        ),
    ]
